apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
      - name: mongos
        image: mongo:8
        command: ["bash", "-c"]
        args:
          - |
            echo "$MONGO_REPLICA_SET_KEY" > /etc/mongo-keyfile;
            chmod 400 /etc/mongo-keyfile;
            exec mongos --configdb=configReplSet/mongo-config-0.mongo-config:27019,mongo-config-1.mongo-config:27019,mongo-config-2.mongo-config:27019 --keyFile /etc/mongo-keyfile --bind_ip_all;
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: MONGO_INITDB_ROOT_PASSWORD
          - name: MONGO_REPLICA_SET_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: MONGO_REPLICA_SET_KEY